### ISSUE TITLE
Error when enabling KeepMyLife 1.4.6 plugin

### ISSUE THREAD

**Issue by lunarys** [anhcraft/KeepMyLife#3]
This exception occurs when starting a server with KeepMyLife 1.4.6 and Craftkit 1.0.7

```
[18:04:34] [Server thread/ERROR]: Error occurred while enabling KeepMyLife v1.4.6 (Is it up to date?)
java.lang.NoSuchMethodError: dev.anhcraft.abif.ABIF.load(Lorg/bukkit/configuration/ConfigurationSection;)Lorg/bukkit/inventory/ItemStack;
        at dev.anhcraft.keepmylife.KeepMyLife.initConf(KeepMyLife.java:76) ~[?:?]
        at dev.anhcraft.keepmylife.KeepMyLife.onEnable(KeepMyLife.java:137) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-ea7e48b-368f4e9]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by anhcraft** [comment]
Confirmed. Will fix soon.
